-- MÓDULO VIII: MANTENEDOR DE GRUPOS
-- Schema: AVAL | Oracle: 19c
--
-- VALIDACIÓN: Concepto "Grupo" NO existe en modelo Oracle real
-- Solo existen: BR_FUNCIONES, BR_OPCIONES_FUNCION, BR_ATRIBUCIONES_OPCION_FUNCION, BR_FUNCIONES_CARGO_RELACIONADO
--
-- Ver modelo base: /docs/develop-plan/DDL/MODELO-ORACLE-REAL.sql

CREATE TABLE AVAL.BR_GRUPOS (
    GRUP_CODIGO         NUMBER(3)       NOT NULL,
    GRUP_NOMBRE         VARCHAR2(100)   NOT NULL,
    GRUP_VIGENTE        NUMBER(1)       DEFAULT 1 NOT NULL,
    GRUP_FECHA_CREACION DATE            DEFAULT SYSDATE NOT NULL,
    
    CONSTRAINT PK_BR_GRUPOS PRIMARY KEY (GRUP_CODIGO),
    CONSTRAINT UK_BR_GRUPOS_NOMBRE UNIQUE (GRUP_NOMBRE),
    CONSTRAINT CK_BR_GRUPOS_VIGENTE CHECK (GRUP_VIGENTE IN (0, 1))
);

COMMENT ON TABLE AVAL.BR_GRUPOS IS 'Grupos de funciones para organización lógica';

CREATE TABLE AVAL.BR_TITULOS (
    TITU_GRUP_CODIGO    NUMBER(3)       NOT NULL,
    TITU_CODIGO         NUMBER(3)       NOT NULL,
    TITU_NOMBRE         VARCHAR2(100)   NOT NULL,
    TITU_ORDEN          NUMBER          DEFAULT 999 NOT NULL,
    
    CONSTRAINT PK_BR_TITULOS PRIMARY KEY (TITU_GRUP_CODIGO, TITU_CODIGO),
    CONSTRAINT FK_BR_TITULOS_GRUPO FOREIGN KEY (TITU_GRUP_CODIGO)
        REFERENCES AVAL.BR_GRUPOS(GRUP_CODIGO)
);

COMMENT ON TABLE AVAL.BR_TITULOS IS 'Títulos organizadores dentro de grupos';
CREATE INDEX IDX_BR_TITULOS_GRUPO ON AVAL.BR_TITULOS(TITU_GRUP_CODIGO);

CREATE TABLE AVAL.BR_TITULOS_FUNCIONES (
    TIFU_GRUP_CODIGO    NUMBER(3)       NOT NULL,
    TIFU_TITU_CODIGO    NUMBER(3)       NOT NULL,
    TIFU_FUNS_CODIGO    NUMBER(3)       NOT NULL,
    
    CONSTRAINT PK_BR_TITULOS_FUNCIONES PRIMARY KEY (TIFU_GRUP_CODIGO, TIFU_TITU_CODIGO, TIFU_FUNS_CODIGO),
    CONSTRAINT FK_BR_TITFUN_TITULO FOREIGN KEY (TIFU_GRUP_CODIGO, TIFU_TITU_CODIGO)
        REFERENCES AVAL.BR_TITULOS(TITU_GRUP_CODIGO, TITU_CODIGO),
    CONSTRAINT FK_BR_TITFUN_FUNCION FOREIGN KEY (TIFU_FUNS_CODIGO)
        REFERENCES AVAL.BR_FUNCIONES(FUNS_CODIGO)
);

COMMENT ON TABLE AVAL.BR_TITULOS_FUNCIONES IS 'Funciones asignadas a títulos de grupos';

CREATE TABLE AVAL.BR_USUARIOS_GRUPOS (
    USGR_GRUP_CODIGO    NUMBER(3)       NOT NULL,
    USGR_RELA_RUT       NUMBER(9)       NOT NULL,
    USGR_FECHA_ASIGNACION DATE          DEFAULT SYSDATE NOT NULL,
    
    CONSTRAINT PK_BR_USUARIOS_GRUPOS PRIMARY KEY (USGR_GRUP_CODIGO, USGR_RELA_RUT),
    CONSTRAINT FK_BR_USGRUP_GRUPO FOREIGN KEY (USGR_GRUP_CODIGO)
        REFERENCES AVAL.BR_GRUPOS(GRUP_CODIGO),
    CONSTRAINT FK_BR_USGRUP_USUARIO FOREIGN KEY (USGR_RELA_RUT)
        REFERENCES AVAL.BR_RELACIONADOS(RELA_RUT)
);

COMMENT ON TABLE AVAL.BR_USUARIOS_GRUPOS IS 'Asignación de usuarios a grupos';
CREATE INDEX IDX_BR_USGRUP_RUT ON AVAL.BR_USUARIOS_GRUPOS(USGR_RELA_RUT);
