-- ===========================================================================
-- Script DDL - Módulo V: Mantenedor de Usuarios Relacionados
-- ===========================================================================
-- Proyecto: Control de Acceso SII
-- Schema: AVAL
-- Base de Datos: Oracle 19c (queilen.sii.cl:1540/koala)
--
-- CRITICAL: Este DDL modifica BR_RELACIONADOS (ALTER) y crea 3 tablas nuevas
-- ===========================================================================

-- ===========================================================================
-- SEQUENCES
-- ===========================================================================

CREATE SEQUENCE SEQ_CARGO_USUARIO_ID
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

COMMENT ON SEQUENCE SEQ_CARGO_USUARIO_ID IS 'Secuencia para IDs de BR_CARGOS_USUARIO';

CREATE SEQUENCE SEQ_FUNCION_USUARIO_ID
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

COMMENT ON SEQUENCE SEQ_FUNCION_USUARIO_ID IS 'Secuencia para IDs de BR_FUNCIONES_USUARIO';

CREATE SEQUENCE SEQ_JURISDICCION_USUARIO_ID
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

COMMENT ON SEQUENCE SEQ_JURISDICCION_USUARIO_ID IS 'Secuencia para IDs de BR_JURISDICCION_USUARIO';

-- ===========================================================================
-- ALTER TABLE: BR_RELACIONADOS
-- Propósito: Agregar columnas para tipo usuario, jurisdicción y vigencias
-- ===========================================================================

-- Columna: Tipo de usuario (INTERNO=SII, EXTERNO=OCM/Notarios/etc)
ALTER TABLE AVAL.BR_RELACIONADOS ADD (
  RELA_TIPO_USUARIO VARCHAR2(10) DEFAULT 'INTERNO' NOT NULL
    CONSTRAINT CHK_RELA_TIPO_USUARIO CHECK (RELA_TIPO_USUARIO IN ('INTERNO', 'EXTERNO'))
);

COMMENT ON COLUMN AVAL.BR_RELACIONADOS.RELA_TIPO_USUARIO IS 'Tipo de usuario: INTERNO (funcionario SII) o EXTERNO (OCM, notarios, CBR, CDE, etc)';

-- Columna: Tipo de jurisdicción
ALTER TABLE AVAL.BR_RELACIONADOS ADD (
  RELA_JURISDICCION VARCHAR2(10) DEFAULT 'SIMPLE' NOT NULL
    CONSTRAINT CHK_RELA_JURISDICCION CHECK (RELA_JURISDICCION IN ('SIMPLE', 'AMPLIADA'))
);

COMMENT ON COLUMN AVAL.BR_RELACIONADOS.RELA_JURISDICCION IS 'Tipo de jurisdicción: SIMPLE (solo región de la unidad) o AMPLIADA (todo el país)';

-- Columnas: Vigencias
ALTER TABLE AVAL.BR_RELACIONADOS ADD (
  RELA_VIGENCIA_INICIO DATE NOT NULL,
  RELA_VIGENCIA_FIN DATE
);

COMMENT ON COLUMN AVAL.BR_RELACIONADOS.RELA_VIGENCIA_INICIO IS 'Fecha inicio vigencia del usuario (obligatorio)';
COMMENT ON COLUMN AVAL.BR_RELACIONADOS.RELA_VIGENCIA_FIN IS 'Fecha fin vigencia del usuario (opcional, NULL = vigente indefinido)';

-- Columna: Unidad principal (para identificar unidad base del usuario)
ALTER TABLE AVAL.BR_RELACIONADOS ADD (
  RELA_UNIDAD_PRINCIPAL NUMBER(4)
);

COMMENT ON COLUMN AVAL.BR_RELACIONADOS.RELA_UNIDAD_PRINCIPAL IS 'Código de unidad de negocio principal del usuario';

-- Columnas de auditoría
ALTER TABLE AVAL.BR_RELACIONADOS ADD (
  RELA_FECHA_CREACION DATE DEFAULT SYSDATE,
  RELA_USUARIO_CREACION VARCHAR2(20),
  RELA_FECHA_MODIFICACION DATE,
  RELA_USUARIO_MODIFICACION VARCHAR2(20)
);

-- Índices para búsquedas frecuentes
CREATE INDEX IDX_RELA_TIPO_USUARIO ON AVAL.BR_RELACIONADOS(RELA_TIPO_USUARIO);
CREATE INDEX IDX_RELA_VIGENCIA ON AVAL.BR_RELACIONADOS(RELA_VIGENCIA_INICIO, RELA_VIGENCIA_FIN);
CREATE INDEX IDX_RELA_EMAIL ON AVAL.BR_RELACIONADOS(UPPER(RELA_EMAIL));

-- ===========================================================================
-- TABLE: BR_CARGOS_USUARIO
-- Propósito: Relacionar usuarios con cargos asignados por unidad
-- ===========================================================================

CREATE TABLE AVAL.BR_CARGOS_USUARIO (
  CAUS_ID                 NUMBER(10) NOT NULL,
  CAUS_RELA_RUT           NUMBER(9) NOT NULL,
  CAUS_CARGO_CODIGO       NUMBER(3) NOT NULL,
  CAUS_UNIDAD_CODIGO      NUMBER(4),
  CAUS_VIGENTE            VARCHAR2(1) DEFAULT 'S' NOT NULL
    CONSTRAINT CHK_CAUS_VIGENTE CHECK (CAUS_VIGENTE IN ('S', 'N')),
  CAUS_FECHA_INICIO       DATE NOT NULL,
  CAUS_FECHA_FIN          DATE,
  CAUS_FECHA_ASIGNACION   DATE DEFAULT SYSDATE,
  CAUS_USUARIO_ASIGNADOR  VARCHAR2(20),
  CONSTRAINT PK_CARGOS_USUARIO PRIMARY KEY (CAUS_ID),
  CONSTRAINT FK_CAUS_RELACIONADO FOREIGN KEY (CAUS_RELA_RUT) 
    REFERENCES AVAL.BR_RELACIONADOS(RELA_RUT) ON DELETE CASCADE,
  CONSTRAINT FK_CAUS_CARGO FOREIGN KEY (CAUS_CARGO_CODIGO) 
    REFERENCES AVAL.BR_CARGOS(CARG_CODIGO),
  CONSTRAINT CHK_CAUS_FECHAS CHECK (CAUS_FECHA_INICIO <= NVL(CAUS_FECHA_FIN, SYSDATE + 99999))
);

COMMENT ON TABLE AVAL.BR_CARGOS_USUARIO IS 'Relación entre usuarios relacionados y cargos asignados por unidad de negocio';
COMMENT ON COLUMN AVAL.BR_CARGOS_USUARIO.CAUS_ID IS 'ID único de la asignación cargo-usuario';
COMMENT ON COLUMN AVAL.BR_CARGOS_USUARIO.CAUS_RELA_RUT IS 'RUT del usuario relacionado (FK a BR_RELACIONADOS)';
COMMENT ON COLUMN AVAL.BR_CARGOS_USUARIO.CAUS_CARGO_CODIGO IS 'Código del cargo asignado (FK a BR_CARGOS)';
COMMENT ON COLUMN AVAL.BR_CARGOS_USUARIO.CAUS_UNIDAD_CODIGO IS 'Código de unidad donde se asigna el cargo';
COMMENT ON COLUMN AVAL.BR_CARGOS_USUARIO.CAUS_VIGENTE IS 'Indica si el cargo está vigente: S=Sí, N=No';
COMMENT ON COLUMN AVAL.BR_CARGOS_USUARIO.CAUS_FECHA_INICIO IS 'Fecha inicio vigencia del cargo';
COMMENT ON COLUMN AVAL.BR_CARGOS_USUARIO.CAUS_FECHA_FIN IS 'Fecha fin vigencia del cargo (NULL = vigente)';

-- Índices
CREATE INDEX IDX_CAUS_USUARIO ON AVAL.BR_CARGOS_USUARIO(CAUS_RELA_RUT);
CREATE INDEX IDX_CAUS_CARGO ON AVAL.BR_CARGOS_USUARIO(CAUS_CARGO_CODIGO);
CREATE INDEX IDX_CAUS_VIGENTE ON AVAL.BR_CARGOS_USUARIO(CAUS_VIGENTE);

-- ===========================================================================
-- TABLE: BR_FUNCIONES_USUARIO
-- Propósito: Funciones específicas asignadas a cada cargo del usuario
-- ===========================================================================

CREATE TABLE AVAL.BR_FUNCIONES_USUARIO (
  FUUS_ID                 NUMBER(10) NOT NULL,
  FUUS_CAUS_ID            NUMBER(10) NOT NULL,
  FUUS_FUNC_CODIGO        NUMBER(3) NOT NULL,
  FUUS_FECHA_ASIGNACION   DATE DEFAULT SYSDATE,
  FUUS_USUARIO_ASIGNADOR  VARCHAR2(20),
  CONSTRAINT PK_FUNCIONES_USUARIO PRIMARY KEY (FUUS_ID),
  CONSTRAINT FK_FUUS_CARGO_USUARIO FOREIGN KEY (FUUS_CAUS_ID) 
    REFERENCES AVAL.BR_CARGOS_USUARIO(CAUS_ID) ON DELETE CASCADE,
  CONSTRAINT FK_FUUS_FUNCION FOREIGN KEY (FUUS_FUNC_CODIGO) 
    REFERENCES AVAL.BR_FUNCIONES(FUNS_CODIGO),
  CONSTRAINT UK_FUUS_CARGO_FUNCION UNIQUE (FUUS_CAUS_ID, FUUS_FUNC_CODIGO)
);

COMMENT ON TABLE AVAL.BR_FUNCIONES_USUARIO IS 'Funciones específicas asignadas a cada cargo del usuario';
COMMENT ON COLUMN AVAL.BR_FUNCIONES_USUARIO.FUUS_ID IS 'ID único de la asignación función-usuario';
COMMENT ON COLUMN AVAL.BR_FUNCIONES_USUARIO.FUUS_CAUS_ID IS 'ID del cargo del usuario (FK a BR_CARGOS_USUARIO, CASCADE)';
COMMENT ON COLUMN AVAL.BR_FUNCIONES_USUARIO.FUUS_FUNC_CODIGO IS 'Código de la función asignada (FK a BR_FUNCIONES)';
COMMENT ON COLUMN AVAL.BR_FUNCIONES_USUARIO.FUUS_FECHA_ASIGNACION IS 'Fecha en que se asignó la función';
COMMENT ON COLUMN AVAL.BR_FUNCIONES_USUARIO.FUUS_USUARIO_ASIGNADOR IS 'RUT del usuario que realizó la asignación';

-- Índices
CREATE INDEX IDX_FUUS_CARGO ON AVAL.BR_FUNCIONES_USUARIO(FUUS_CAUS_ID);
CREATE INDEX IDX_FUUS_FUNCION ON AVAL.BR_FUNCIONES_USUARIO(FUUS_FUNC_CODIGO);

-- ===========================================================================
-- TABLE: BR_JURISDICCION_USUARIO
-- Propósito: Gestionar multi-jurisdicción (apoyo temporal en otras unidades)
-- ===========================================================================

CREATE TABLE AVAL.BR_JURISDICCION_USUARIO (
  JUUR_ID                 NUMBER(10) NOT NULL,
  JUUR_RELA_RUT           NUMBER(9) NOT NULL,
  JUUR_UNIDAD_APOYO       NUMBER(4),
  JUUR_FECHA_INICIO       DATE NOT NULL,
  JUUR_FECHA_FIN          DATE NOT NULL,
  JUUR_MOTIVO             VARCHAR2(200),
  JUUR_FECHA_REGISTRO     DATE DEFAULT SYSDATE,
  JUUR_USUARIO_REGISTRO   VARCHAR2(20),
  CONSTRAINT PK_JURISDICCION_USUARIO PRIMARY KEY (JUUR_ID),
  CONSTRAINT FK_JUUR_RELACIONADO FOREIGN KEY (JUUR_RELA_RUT) 
    REFERENCES AVAL.BR_RELACIONADOS(RELA_RUT) ON DELETE CASCADE,
  CONSTRAINT CHK_JUUR_FECHAS CHECK (JUUR_FECHA_INICIO < JUUR_FECHA_FIN)
);

COMMENT ON TABLE AVAL.BR_JURISDICCION_USUARIO IS 'Períodos de apoyo multi-jurisdicción en unidades alternas';
COMMENT ON COLUMN AVAL.BR_JURISDICCION_USUARIO.JUUR_ID IS 'ID único del período de multi-jurisdicción';
COMMENT ON COLUMN AVAL.BR_JURISDICCION_USUARIO.JUUR_RELA_RUT IS 'RUT del usuario con multi-jurisdicción';
COMMENT ON COLUMN AVAL.BR_JURISDICCION_USUARIO.JUUR_UNIDAD_APOYO IS 'Código de unidad donde presta apoyo temporal';
COMMENT ON COLUMN AVAL.BR_JURISDICCION_USUARIO.JUUR_FECHA_INICIO IS 'Fecha inicio del período de apoyo';
COMMENT ON COLUMN AVAL.BR_JURISDICCION_USUARIO.JUUR_FECHA_FIN IS 'Fecha fin del período de apoyo';
COMMENT ON COLUMN AVAL.BR_JURISDICCION_USUARIO.JUUR_MOTIVO IS 'Motivo o justificación del apoyo';

-- Índices
CREATE INDEX IDX_JUUR_USUARIO ON AVAL.BR_JURISDICCION_USUARIO(JUUR_RELA_RUT);
CREATE INDEX IDX_JUUR_FECHAS ON AVAL.BR_JURISDICCION_USUARIO(JUUR_FECHA_INICIO, JUUR_FECHA_FIN);

-- ===========================================================================
-- VALIDACIONES Y QUERIES DE PRUEBA
-- ===========================================================================

-- Verificar estructura BR_RELACIONADOS
-- DESCRIBE AVAL.BR_RELACIONADOS;

-- Verificar tablas creadas
-- SELECT table_name FROM user_tables 
-- WHERE table_name IN ('BR_CARGOS_USUARIO', 'BR_FUNCIONES_USUARIO', 'BR_JURISDICCION_USUARIO')
-- ORDER BY table_name;

-- Verificar secuencias
-- SELECT sequence_name, last_number FROM user_sequences 
-- WHERE sequence_name LIKE 'SEQ_%USUARIO%'
-- ORDER BY sequence_name;

-- Query de prueba: Usuario con todos sus cargos y funciones
-- SELECT 
--   r.RELA_RUT,
--   r.RELA_NOMBRE || ' ' || r.RELA_PATERNO || ' ' || r.RELA_MATERNO as nombre_completo,
--   r.RELA_TIPO_USUARIO,
--   r.RELA_JURISDICCION,
--   c.CARG_DESCRIPCION as cargo,
--   cu.CAUS_VIGENTE,
--   f.FUNS_DESCRIPCION as funcion
-- FROM AVAL.BR_RELACIONADOS r
-- LEFT JOIN AVAL.BR_CARGOS_USUARIO cu ON r.RELA_RUT = cu.CAUS_RELA_RUT
-- LEFT JOIN AVAL.BR_CARGOS c ON cu.CAUS_CARGO_CODIGO = c.CARG_CODIGO
-- LEFT JOIN AVAL.BR_FUNCIONES_USUARIO fu ON cu.CAUS_ID = fu.FUUS_CAUS_ID
-- LEFT JOIN AVAL.BR_FUNCIONES f ON fu.FUUS_FUNC_CODIGO = f.FUNS_CODIGO
-- WHERE r.RELA_RUT = :rut
-- ORDER BY cu.CAUS_ID, fu.FUUS_ID;

-- ===========================================================================
-- ROLLBACK (solo para testing, NO ejecutar en producción)
-- ===========================================================================

-- DROP INDEX IDX_JUUR_FECHAS;
-- DROP INDEX IDX_JUUR_USUARIO;
-- DROP TABLE AVAL.BR_JURISDICCION_USUARIO CASCADE CONSTRAINTS;

-- DROP INDEX IDX_FUUS_FUNCION;
-- DROP INDEX IDX_FUUS_CARGO;
-- DROP TABLE AVAL.BR_FUNCIONES_USUARIO CASCADE CONSTRAINTS;

-- DROP INDEX IDX_CAUS_VIGENTE;
-- DROP INDEX IDX_CAUS_CARGO;
-- DROP INDEX IDX_CAUS_USUARIO;
-- DROP TABLE AVAL.BR_CARGOS_USUARIO CASCADE CONSTRAINTS;

-- DROP SEQUENCE SEQ_JURISDICCION_USUARIO_ID;
-- DROP SEQUENCE SEQ_FUNCION_USUARIO_ID;
-- DROP SEQUENCE SEQ_CARGO_USUARIO_ID;

-- ALTER TABLE AVAL.BR_RELACIONADOS DROP COLUMN RELA_USUARIO_MODIFICACION;
-- ALTER TABLE AVAL.BR_RELACIONADOS DROP COLUMN RELA_FECHA_MODIFICACION;
-- ALTER TABLE AVAL.BR_RELACIONADOS DROP COLUMN RELA_USUARIO_CREACION;
-- ALTER TABLE AVAL.BR_RELACIONADOS DROP COLUMN RELA_FECHA_CREACION;
-- ALTER TABLE AVAL.BR_RELACIONADOS DROP COLUMN RELA_UNIDAD_PRINCIPAL;
-- ALTER TABLE AVAL.BR_RELACIONADOS DROP COLUMN RELA_VIGENCIA_FIN;
-- ALTER TABLE AVAL.BR_RELACIONADOS DROP COLUMN RELA_VIGENCIA_INICIO;
-- ALTER TABLE AVAL.BR_RELACIONADOS DROP COLUMN RELA_JURISDICCION;
-- ALTER TABLE AVAL.BR_RELACIONADOS DROP COLUMN RELA_TIPO_USUARIO;
